### ISSUE TITLE
Push to support geo queries, limits and sorting? 

### ISSUE THREAD

**Issue by MadManMathew** [Retsly/support#1]
### Problem
Currently some of the query mechanisms we support in our API are not also supported for our push feature. Geo queries and Limits to be specific.
There is also no warnings and they are omitted. 

### Tasks
 - [x] decided which queries should be valid
 - [x] implement/ allow them for push as well.
 - [x] throw warnings or error if queries are invalid or non supported.

**Comment by kregensberg** [comment]
Closing. A rewrite of push architecture has been implemented and will enter product soon.
